<!DOCTYPE html>
<html lang="en">

<head>
    <?php require_once('./head_google_analytics_and_icon.php'); ?>
    <title>Cookie Policy</title>
    <!-- CSS -->
    <link rel="stylesheet" href="./assets/css/init.css">
    <link rel="stylesheet" href="./assets/css/cookie-policy.css">
    <!-- JS -->
    <script src="./assets/js/jQuery1.7.2.min.js"></script>
    <script src="./assets/js/GSAP3.10.4.min.js"></script>
    <script src="./assets/js/ScrollTrigger3.10.4.min.js"></script>
    <script src="./assets/js/ScrollToPlugin3.10.4.min.js"></script>
</head>

<body>
    <div class="cursor hide"></div>
    <div class="cursor__follower hide"></div>
    <!-- Nav -->
    <header>
        <?php require_once('./header_content.php'); ?>
    </header>

    <main class="main">

        <!-- Cookie section -->
        <section class="seccionCookie">
            <div class="seccionCookie__contenedor">
                <h1 class="seccionCookie__h1">Cookie Policy</h1>
                <div class="seccionCookie__indice">
                    <ul>
                        <li class="seccionCookie__li">
                            <a class="seccionCookie__titulo" href="javascript:void(0)">
                                <span>Definitions and Key Terms</span>
                            </a>
                            <p class="seccionCookie__parrafo">To help explain things as clearly as possible in this
                                Cookie Policy, every time any of these terms are referenced, are strictly defined as:
                            </p>
                            <p>
                                -Cookie: small amount of data generated by a website and saved by your web browser. It
                                is used to identify your browser, provide analytics, remember information about you such
                                as your language preference or login information.
                                <br>
                                -Company: when this policy mentions “Company,” “we,” “us,” or “our,” it refers to Hdden
                                Forms, that is responsible for your information under this Cookie Policy.
                                <br>
                                -Device: any internet connected device such as a phone, tablet, computer or any other
                                device that can be used to visit Hdden Forms and use the services.
                                <br>
                                -Personal Data: any information that directly, indirectly, or in connection with other
                                information — including a personal identification number — allows for the identification
                                or identifiability of a natural person.
                                <br>
                                -Service: refers to the service provided by Hdden Forms as described in the relative
                                terms (if available) and on this platform.
                                <br>
                                -Third-party service: refers to advertisers, contest sponsors, promotional and marketing
                                partners, and others who provide our content or whose products or services we think may
                                interest you.
                                <br>
                                -Website: Hdden Forms."’s" site, which can be accessed via this URL:
                                https://hddenforms.com/
                                <br>
                                -You: a person or entity that is registered with Hdden Forms to use the Services.
                            </p>
                        </li>
                        <li class="seccionCookie__li">
                            <a class="seccionCookie__titulo" href="javascript:void(0)">
                                <span>Introduction</span>
                            </a>
                            <p class="seccionCookie__parrafo">This Cookie Policy explains how Hdden Forms and its
                                affiliates (collectively "Hdden Forms", "we", "us", and "ours"), use cookies and similar
                                technologies to recognize you when you visit our website, including without limitation
                                https://hddenforms.com/ and any related URLs, mobile or localized versions and related
                                domains / sub-domains ("Websites"). It explains what these technologies are and why we
                                use them, as well as the choices for how to control them.</p>
                        </li>
                        <li class="seccionCookie__li active">
                            <a class="seccionCookie__titulo" href="javascript:void(0)">
                                <span>What is a cookie?</span>
                            </a>
                            <p class="seccionCookie__parrafo">A cookie is a small text file that is stored on your
                                computer or other internet connected device in order to identify your browser, provide
                                analytics, remember information about you such as your language preference or login
                                information. They're completely safe and can't be used to run programs or deliver
                                viruses to your device.</p>
                        </li>
                        <li class="seccionCookie__li">
                            <a class="seccionCookie__titulo" href="javascript:void(0)">
                                <span>Why do we use cookies?</span>
                            </a>
                            <p class="seccionCookie__parrafo">We use first party and/or third party cookies on our
                                website for various purposes such as:</p>
                            <p>
                                -To facilitate the operation and functionality of our website;
                                <br>
                                -To improve your experience of our website and make navigating around them quicker and
                                easier;
                                <br>
                                -To allow us to make a bespoke user experience for you and for us to understand what is
                                useful or of interest to you;
                                <br>
                                -To analyze how our website is used and how best we can customize it;
                                <br>
                                -To identify future prospects and personalize marketing and sales interactions with it;
                                <br>
                                -To facilitate the tailoring of online advertising to your interests.
                            </p>
                        </li>
                        <li class="seccionCookie__li">
                            <a class="seccionCookie__titulo" href="javascript:void(0)">
                                <span>What type of cookies does Hdden Forms use?</span>
                            </a>
                            <p class="seccionCookie__parrafo">Cookies can either be session cookies or persistent
                                cookies. A session cookie expires automatically when you close your browser. A
                                persistent cookie will remain until it expires or you delete your cookies. Expiration
                                dates are set in the cookies themselves; some may expire after a few minutes while
                                others may expire after multiple years. Cookies placed by the website you’re visiting
                                are called “first party cookies”.</p>
                            <p>Strictly Necessary cookies are necessary for our website to function and cannot be
                                switched off in our systems. They are essential in order to enable you to navigate
                                around the website and use its features. If you remove or disable these cookies, we
                                cannot guarantee that you will be able to use our website.</p>
                            <p>We use the following types of cookies in our website:</p>
                            <p>Errors and Omissions Disclaimer</p>
                            <p>Hdden Forms is not responsible for any content, code or any other imprecision.</p>
                            <p>Hdden Forms does not provide warranties or guarantees.</p>
                            <p>In no event shall Hdden Forms be liable for any special, direct, indirect, consequential,
                                or incidental damages or any damages whatsoever, whether in an action of contract,
                                negligence or other tort, arising out of or in connection with the use of the Service or
                                the contents of the Service. Hdden Forms reserves the right to make additions,
                                deletions, or modifications to the contents on the Service at any time without prior
                                notice.</p>
                        </li>
                        <li class="seccionCookie__li">
                            <a class="seccionCookie__titulo" href="javascript:void(0)">
                                <span>General Disclaimer</span>
                            </a>
                            <p class="seccionCookie__parrafo">The Hdden Forms Service and its contents are provided "as
                                is" and "as available" without any warranty or representations of any kind, whether
                                express or implied. Hdden Forms is a distributor and not a publisher of the content
                                supplied by third parties; as such, Hdden Forms exercises no editorial control over such
                                content and makes no warranty or representation as to the accuracy, reliability or
                                currency of any information, content, service or merchandise provided through or
                                accessible via the Hdden Forms Service. Without limiting the foregoing, Hdden Forms
                                specifically disclaims all warranties and representations in any content transmitted on
                                or in connection with the Hdden Forms Service or on sites that may appear as links on
                                the Hdden Forms Service, or in the products provided as a part of, or otherwise in
                                connection with, the Hdden Forms Service, including without limitation any warranties of
                                merchantability, fitness for a particular purpose or non-infringement of third party
                                rights. No oral advice or written information given by Hdden Forms or any of its
                                affiliates, employees, officers, directors, agents, or the like will create a warranty.
                                Price and availability information is subject to change without notice. Without limiting
                                the foregoing, Hdden Forms does not warrant that the Hdden Forms Service will be
                                uninterrupted, uncorrupted, timely, or error-free.</p>
                        </li>
                        <li class="seccionCookie__li">
                            <a class="seccionCookie__titulo" href="javascript:void(0)">
                                <span>Essential Cookies</span>
                            </a>
                            <p class="seccionCookie__parrafo">We use essential cookies to make our website work. These
                                cookies are strictly necessary to enable core functionality such as security, network
                                management, your cookie preferences and accessibility. Without them you wouldn't be able
                                to use basic services. You may disable these by changing your browser settings, but this
                                may affect how the Websites function.</p>
                        </li>
                        <li class="seccionCookie__li">
                            <a class="seccionCookie__titulo" href="javascript:void(0)">
                                <span>Performance and Functionality Cookies</span>
                            </a>
                            <p class="seccionCookie__parrafo">These cookies are used to enhance the performance and
                                functionality of our website but are non-essential to their use. However, without these
                                cookies, certain functionality like videos may become unavailable or you would be
                                required to enter your login details every time you visit the website as we would not be
                                able to remember that you had logged in previously.</p>
                        </li>
                        <li class="seccionCookie__li">
                            <a class="seccionCookie__titulo" href="javascript:void(0)">
                                <span>How you can manage cookies?</span>
                            </a>
                            <p class="seccionCookie__parrafo">Most browsers allow you to control cookies through their
                                'settings' preferences. However, if you limit the ability of websites to set cookies,
                                you may worsen your overall user experience, since it will no longer be personalized to
                                you. It may also stop you from saving customized settings like login information.
                                Browser manufacturers provide help pages relating to cookie management in their
                                products.</p>
                            <p>Browser manufacturers provide help pages relating to cookie management in their products.
                                Please see below for more information.</p>
                            <ul class="seccionCookie__li--navegadores">
                                <li>-Google Chrome</li>
                                <li>-Internet Explorer</li>
                                <li>-Mozilla Firefox</li>
                                <li>-Safari (Desktop)</li>
                                <li>-Safari (Mobile)</li>
                                <li>-Android Browser</li>
                                <li>-Opera</li>
                                <li>-Opera Mobile</li>
                            </ul>
                        </li>
                        <li class="seccionCookie__li">
                            <a class="seccionCookie__titulo" href="javascript:void(0)">
                                <span>Blocking and disabling cookies and similar technologies</span>
                            </a>
                            <p class="seccionCookie__parrafo">Wherever you're located you may also set your browser to
                                block cookies and similar technologies, but this action may block our essential cookies
                                and prevent our website from functioning properly, and you may not be able to fully
                                utilize all of its features and services. You should also be aware that you may also
                                lose some saved information (e.g. saved login details, site preferences) if you block
                                cookies on your browser. Different browsers make different controls available to you.
                                Disabling a cookie or category of cookie does not delete the cookie from your browser,
                                you will need to do this yourself from within your browser, you should visit your
                                browser's help menu for more information.</p>
                        </li>
                        <li class="seccionCookie__li">
                            <a class="seccionCookie__titulo" href="javascript:void(0)">
                                <span>Changes To Our Cookie Policy</span>
                            </a>
                            <p class="seccionCookie__parrafo">We may change our Service and policies, and we may need to
                                make changes to this Cookie Policy so that they accurately reflect our Service and
                                policies. Unless otherwise required by law, we will notify you (for example, through our
                                Service) before we make changes to this Cookie Policy and give you an opportunity to
                                review them before they go into effect. Then, if you continue to use the Service, you
                                will be bound by the updated Cookie Policy. If you do not want to agree to this or any
                                updated Cookie Policy, you can delete your account.</p>
                        </li>
                        <li class="seccionCookie__li">
                            <a class="seccionCookie__titulo" href="javascript:void(0)">
                                <span>Your Consent</span>
                            </a>
                            <p class="seccionCookie__parrafo">By using our website, registering an account, or making a
                                purchase, you hereby consent to our Cookie Policy and agree to its terms.</p>
                        </li>
                        <li class="seccionCookie__li">
                            <a class="seccionCookie__titulo" href="javascript:void(0)">
                                <span>Contact Us</span>
                            </a>
                            <p class="seccionCookie__parrafo">Don't hesitate to contact us if you have any questions
                                regarding our Cookie Policy.</p>
                            <p> -Via Email: info@hddenforms.com</p>
                        </li>
                    </ul>
                </div>
            </div>
        </section>
    </main>
    
    <footer>
        <?php require_once('./footer_content.php'); ?>
    </footer>
    
    <script type="text/javascript" src="./assets/js/init.js"></script>
    <script>
        let navbar__logohdden = document.querySelector('.navbar__logohdden')
        navbar__logohdden.addEventListener("click", () => {
            this.window.location.href = 'index.php'
        })

        let indice = document.querySelectorAll('.seccionCookie__li')
        indice.forEach(item => {
            item.addEventListener('click', event => {

                if (item.classList.contains('active')) {
                    item.classList.remove('active')
                    return true
                } else {
                    indice.forEach(c => c.classList.remove('active'))
                    item.classList.add('active')
                }
            })
        })
    </script>
</body>

</html>